version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/apps/politico-civic/
  - source: /confs/awslogs.conf
    destination: /var/awslogs/etc/
hooks:
  AfterInstall:
    - location: deploy/postinstall.sh
      timeout: 300
      runas: ubuntu
permissions:
  - object: /home/ubuntu/apps/politico-civic/deploy
    pattern: "**"
    owner: ubuntu
    mode: 777
    type:
      - file
