version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/apps/politico-civic/
  - source: /confs/awslogs.conf
    destination: /var/awslogs/etc/awslogs.conf
hooks:
  AfterInstall:
    - location: deploy/postinstall.sh
      timeout: 300
      runas: ubuntu
