import os

ELECTIONNIGHT_AWS_ACCESS_KEY_ID = os.getenv("AWS_ACCESS_KEY_ID", None)
ELECTIONNIGHT_AWS_SECRET_ACCESS_KEY = os.getenv("AWS_SECRET_ACCESS_KEY", None)
ELECTIONNIGHT_AWS_REGION = "us-east-1"
ELECTIONNIGHT_AWS_S3_BUCKET = os.getenv("ELECTIONNIGHT_AWS_S3_BUCKET")
ELECTIONNIGHT_AWS_S3_STATIC_ROOT = os.getenv(
    "ELECTIONNIGHT_AWS_S3_STATIC_ROOT"
)
