import os

TRACKER_AWS_ACCESS_KEY_ID = os.getenv("AWS_ACCESS_KEY_ID", None)
TRACKER_AWS_SECRET_ACCESS_KEY = os.getenv("AWS_SECRET_ACCESS_KEY", None)
TRACKER_AWS_REGION = "us-east-1"
TRACKER_AWS_S3_BUCKET = os.getenv("ELECTIONNIGHT_AWS_S3_BUCKET")
TRACKER_AWS_S3_STATIC_ROOT = os.getenv("ELECTIONNIGHT_AWS_S3_STATIC_ROOT")

TRACKER_TWITTER_CONSUMER_KEY = os.getenv("TRACKER_TWITTER_CONSUMER_KEY")
TRACKER_TWITTER_CONSUMER_SECRET = os.getenv("TRACKER_TWITTER_CONSUMER_SECRET")
TRACKER_TWITTER_ACCESS_TOKEN_KEY = os.getenv(
    "TRACKER_TWITTER_ACCESS_TOKEN_KEY"
)
TRACKER_TWITTER_ACCESS_TOKEN_SECRET = os.getenv(
    "TRACKER_TWITTER_ACCESS_TOKEN_SECRET"
)

TRACKER_TWITTER_WHITELIST = [
    "politicoscott",
    "politico_steve",
    "politicocharlie",
    "ec_schneider",
    "jamesarkin",
    "tylrfishr",
]

SLACKFORMS_SLACK_VERIFICATION_TOKEN = os.getenv(
    "SLACKFORMS_SLACK_VERIFICATION_TOKEN"
)
SLACKFORMS_CALLBACK_URL = "https://politicoapps.com/slack-forms/callback/"
SLACKFORMS_VERIFICATION_TOKEN = os.getenv("SLACKFORMS_VERIFICATION_TOKEN")
SLACKFORMS_FEEDBACK_CHANNEL = os.getenv("SLACKFORMS_FEEDBACK_CHANNEL")
